language: ruby
cache: bundler
rvm:
- 2.7.0
services:
- postgresql
jobs:
  include:
  - stage: test
    name: Test
    script:
    - bundle exec rake db:setup RAILS_ENV=test
    - bundle exec rake spec RAILS_ENV=test
stages:
- name: test
env:
  global:
  - secure: U0lu1A4sdC5vFAjFzsuy6baPFjVmY4C8Dp181wX43BbRJlSAP3TTccK6esRSHGrx/dd9eT1xglIZiUFriyqFd7GEqnQp8WpPtskTnnf8vJtFbDfqbk0P5v7K//ko+YZMFeltzPHjaAgUHe1BY36FeEs6VjerXCOqlfUaYBM73NamRqFyG51Onaou/hXd73Tmd2wLcDCatBeR2VefN3eHe+9EnvhZIPGQTJ9uzQ33XEGaa92ui/8cXkUbms13z8n2/rizAyUfwe8TL93urZfnJTqFMWY1ASRLFNlNFiYJBoxuAV/JMiUeZeoWGjjzQDOzGJgOG9w2VUETVpVYcPoxjDVy7QQ8hUIlE5wEneHTxIX25Mia/+jR30nEKgNznH3r4LjrspHJ5zh8qHLce5S37w5Pb7nfTj5YT7uQ09f2s7yE7ptE2dqg5olj6Oc0RF1ZY37k6MqPa/QK4hbBaTQHt+lZYlGhKN4696Lj8DLlObqI2GikAOr2tOgEIaOfq6U2BcXz+GTDDovY7PP/PHIhz74bEixZm4oS8T9hB7CvfrDl9G00O3IO9W19E0WeErT9ciCRX19et8P0Vapm+Pvb7JAeeEmzkhVhclgxOU9cHx/VKF99bPaTGTX3Ustcrl/I5MZhKFW+SGffft2wbytUZGHSIEbogzGRvFWATwiQl0E=
  - secure: POn3eOdXtg8WGDUPqb1BlmpBkKYGIxz9IgB9zxspXIE3xNoVwuIUlO/d8lDhFJ/hytR7XcahSz4zcTgzvUvfhpZ6tBs2NKnt/pSn2Y5SQNfblV5sZterA/AVe1Q/BcwZzi7sJvuJ6GIyRhiM+7xx2aT8O+X+86tHUcoMea2Gkbym4aRuilgA0tOw6bHoXpzsCUztan0EXm89bkWvtwIlQCWLQ/10UWjaTKJOwOjRh6L/Yo7Kgc+PhW04Et15R2Gbs31aJiJWfZZn9h9N7gmR+FTRcSkpun6zMZX3XTo/qubw0D67RbdhejIxG4dWW8XkypmveShJocR0m1+BL70ltgfVJbLtdKaTm9Atp6T5zstPV0w9wYKNlDfN3TgSvsPJRIPF+OtHHNgB4Z/vqh6irSs/azWgNGcFxEAU6sr83sclspdW/ahicbf3CJ3pGFknQhtGin6lXi5jAJXVN0GmK0tErKT79I5nwv4JAr+9ugahWbtI2DFgq1nprnFq/rFsWNz95V/yc4Va1K7cZrun5VJgvSxLYgK0SYoXDjbAeeA0na7x9eF7xx5Zlh+9lwGebs1pWrVhWjamUKH67QfpPJBQdS/b51KNjF4YoNjAdcycMHWC0TblBO+rQc/sM6ttsWyZHkvx9mTVG4+yU4OuFEh1JVspafleG+R0MvHgksI=
