language: ruby
cache: bundler
rvm:
- 2.7.0
services:
- postgresql
jobs:
  include:
  - stage: test
    name: Test
    script:
    - bundle exec rake db:setup RAILS_ENV=test
    - bundle exec rake spec RAILS_ENV=test
stages:
- name: test
